app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
   path('sample3/',sample3,name='sample3'),
   path('sample4/',sample4,name='sample4'),
 ]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import app2
from app1.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample1/',sample1,name='sample1'),
    path('sample2/',sample2,name='sample2'),
    path('app2/',include('app2.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def sample1(request):
    return render(request,'sample1.html')

def sample2(request):
    return render(request,'sample2.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def sample3(request):
    return render(request,'sample3.html')

def sample4(request):
    return render(request,'sample4.html')

templates/sample1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>SAMPLE1</h1>
        <h2>NAME  : Deepika gandham</h2>
        <h2>AGE   :  21</h2>
        <h2>FATHER'S NAME:Anjaneyulu naidu</h2>
        <h2>MOTHER'S NAME:Nageswaramma</h2>
        <a href="{% url 'sample2' %}">sample2</a>
        <a href="{% url 'app2:sample3' %}">sample3</a>
        <a href="{% url 'app2:sample4' %}">sample4</a>
    </center>
    
</body>
</html>

templates/sample2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>SAMPLE2</h1>
        <a href="{% url 'sample1' %}">SAMPLE1</a>
        <a href="{% url 'app2:sample3' %}">sample3</a>
        <a href="{% url 'app2:sample4' %}">sample4</a>
    </center>
</body>
</html>

templates/sample3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>sample3</h1>
        <a href="{% url 'sample2' %}">sample2</a>
        <a href="{% url 'sample1' %}">SAMPLE1</a>
        <a href="{% url 'app2:sample4' %}">sample4</a>
    </center>
    
</body>
</html>

templates/sample4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>sample4</h1>
        <a href="{% url 'sample2' %}">sample2</a>
        <a href="{% url 'sample1' %}">SAMPLE1</a>
        <a href="{% url 'app2:sample3' %}">sample3</a>
    </center>
</body>
</html>